# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire', verbose_name='问卷'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='count',
            field=models.IntegerField(default=1, verbose_name='班级人数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(1, '单选'), (2, '建议'), (3, '打分(1~10分)')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=64, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='caption',
            field=models.CharField(max_length=64, verbose_name='问卷名称'),
        ),
        migrations.AlterField(
            model_name='radioquestion',
            name='content',
            field=models.CharField(max_length=64, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='radioquestion',
            name='score',
            field=models.IntegerField(verbose_name='分值'),
        ),
    ]
