# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171205_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ManyToManyField(to='polls.Questionnaire', verbose_name='问卷'),
        ),
    ]
