# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171207_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='radioquestion',
            name='question',
            field=models.ManyToManyField(to='polls.Question', verbose_name='问题'),
        ),
    ]
